export type AdvicePriority = "hoog" | "middel" | "laag";

export type QuestionAdvice = {
  consequence: string;
  betterSetup: string;
  cloud1Fit: string;
  priority: AdvicePriority;
  risk: string;
  firstStep: string;
};

export const QUESTION_ADVICE: Record<string, QuestionAdvice> = {
  "1.1": {
    consequence: "Nieuwe medewerkers zijn later productief en laptops worden niet altijd op dezelfde veilige manier ingericht.",
    betterSetup: "Werk met een standaard werkplekprofiel, automatische installatie en vooraf ingestelde beveiligingsregels.",
    cloud1Fit: "Cloud ÉÉN Werkplek Standaard kan helpen om onboarding voorspelbaar te maken met moderne Microsoft 365 werkplekken.",
    priority: "hoog",
    risk: "Nieuwe medewerkers komen op dag 1 niet aan het werk. Dat kost gemiddeld 2–3 dagen productiviteit per persoon — en bij snelle groei loopt dat snel op.",
    firstStep: "Maak een checklist van de stappen die u nu handmatig doet bij elke nieuwe medewerker. Zo ziet u direct waar de bottlenecks zitten.",
  },
  "1.2": {
    consequence: "Zonder centraal beheer is lastig te zien welke apparaten veilig zijn, versleuteld zijn en updates ontvangen.",
    betterSetup: "Beheer laptops centraal, inclusief apparaatregistratie, encryptie, beleid en automatische controles.",
    cloud1Fit: "Cloud ÉÉN Werkplek Standaard sluit aan bij centraal werkplekbeheer en basisbeveiliging.",
    priority: "hoog",
    risk: "Zonder centraal overzicht weet u niet welke laptops versleuteld zijn, welke updates missen en welk apparaat gevaar loopt bij een incident.",
    firstStep: "Controleer in Microsoft 365 Beheercentrum onder 'Apparaten' hoeveel apparaten er staan ingeschreven. Staat die lijst er niet? Dan heeft u geen overzicht.",
  },
  "1.3": {
    consequence: "Zakelijke data kan op prive-telefoons blijven staan of gedeeld worden buiten de bedrijfsomgeving.",
    betterSetup: "Scheid werk en prive, beveilig zakelijke apps en maak bedrijfsdata op afstand wisbaar.",
    cloud1Fit: "Cloud ÉÉN kan mobiel device- en appbeheer inrichten als onderdeel van een beheerde werkplek.",
    priority: "middel",
    risk: "Een medewerker met zakelijke e-mail op zijn privételefoon neemt bij vertrek bedrijfsdata mee. U kunt dat op afstand niet wissen.",
    firstStep: "Vraag uw medewerkers welke zakelijke apps ze op hun privételefoon gebruiken. De uitkomst is meestal een verrassing.",
  },
  "1.4": {
    consequence: "Bij vertrek kunnen oude accounts, mailboxen of apps langer open blijven dan bedoeld.",
    betterSetup: "Richt een vaste offboardingflow in waarbij toegang, dataoverdracht en licenties direct worden afgehandeld.",
    cloud1Fit: "Cloud ÉÉN Werkplek Standaard kan helpen met vaste processen voor gebruikersbeheer en toegang.",
    priority: "hoog",
    risk: "Een ex-medewerker die na vertrek nog maanden toegang heeft tot uw systemen is geen hypothetisch risico — het is iets dat bij bijna elk bedrijf zonder vast offboardingproces voorkomt.",
    firstStep: "Controleer in Microsoft 365 Beheercentrum of de accounts van ex-medewerkers van het afgelopen jaar zijn geblokkeerd of verwijderd.",
  },
  "1.5": {
    consequence: "Verouderde software vergroot de kans op storingen en misbruik van bekende kwetsbaarheden.",
    betterSetup: "Plan updates centraal, bewaak installaties en rapporteer apparaten die achterblijven.",
    cloud1Fit: "Cloud ÉÉN Werkplek Premium of aanvullend beheer kan updatebeleid en monitoring structureel maken.",
    priority: "hoog",
    risk: "90% van de succesvolle cyberaanvallen maakt gebruik van kwetsbaarheden waarvoor al maanden een patch beschikbaar was. Updates zijn uw goedkoopste beveiliging.",
    firstStep: "Open Windows Update op 3 willekeurige laptops. Hoeveel updates staan er klaar? Dat geeft direct inzicht in uw patchachterstand.",
  },
  "1.6": {
    consequence: "Medewerkers verliezen flexibiliteit of werken via oplossingen die niet overal even veilig zijn.",
    betterSetup: "Maak werken vanaf kantoor, thuis en onderweg mogelijk met cloudtoegang en controles op gebruiker en apparaat.",
    cloud1Fit: "Cloud ÉÉN Werkplek Standaard kan een moderne werkplek neerzetten die vanaf meerdere locaties goed werkt.",
    priority: "middel",
    risk: "Medewerkers die thuis via onbeveiligde verbindingen werken, doen dat waarschijnlijk al — of ze u dat nu vertellen of niet.",
    firstStep: "Vraag 5 medewerkers hoe ze thuis verbinding maken met bedrijfssystemen. Gebruiken ze VPN of werken ze direct? Weten ze het verschil?",
  },
  "1.7": {
    consequence: "Shadow IT brengt onzichtbare risico's mee: data buiten de controle van het bedrijf, lekken en AVG-overtredingen.",
    betterSetup: "Stel een lijst op met goedgekeurde tools, communiceer die actief en blokkeer of signaleer afwijkingen.",
    cloud1Fit: "Cloud ÉÉN kan helpen met Microsoft 365-beleidsregels die ongecontroleerd gebruik van externe cloudopslag beperken.",
    priority: "hoog",
    risk: "Gratis tools als WhatsApp, Dropbox of ChatGPT worden door medewerkers gebruikt voor werkdocumenten — zonder dat u dat weet en zonder AVG-compliance.",
    firstStep: "Vraag uw team welke tools ze gebruiken die niet officieel zijn goedgekeurd. De lijst is vrijwel altijd langer dan verwacht.",
  },
  "1.8": {
    consequence: "Verouderde hardware vertraagt medewerkers, verhoogt storingskansen en is moeilijker te beveiligen met moderne beleidsregels.",
    betterSetup: "Hanteer een vaste vervangingscyclus van 4–5 jaar, houd een apparaatregister bij en plan vervanging proactief.",
    cloud1Fit: "Cloud ÉÉN Werkplek Standaard kan helpen met hardware-overzicht, levenscyclusbeheer en gestandaardiseerde vervangingsstrategieën.",
    priority: "middel",
    risk: "Een laptop van 6 jaar oud kost in verloren tijd door traagheid en storingen meer dan een nieuwe laptop zou kosten — en hij is niet meer te beveiligen met modern beleid.",
    firstStep: "Noteer het aanschafjaar van de 5 oudste apparaten in uw organisatie. Alles ouder dan 5 jaar staat in de risicozone.",
  },
  "2.1": {
    consequence: "Alleen een wachtwoord is kwetsbaar; gestolen wachtwoorden zijn nog steeds een veelvoorkomende ingang.",
    betterSetup: "Verplicht MFA en voeg toegangsregels toe op basis van locatie, apparaat en risico.",
    cloud1Fit: "Cloud ÉÉN Werkplek Premium past goed bij sterkere Microsoft 365 beveiliging en Conditional Access.",
    priority: "hoog",
    risk: "Zonder MFA is één gestolen wachtwoord voldoende om toegang te krijgen tot alle bedrijfsdata. Dit is de meest voorkomende oorzaak van datalekken bij MKB.",
    firstStep: "Ga naar Microsoft 365 Beheercentrum → Beveiliging → MFA. Controleer voor hoeveel gebruikers MFA actief is. Elke gebruiker zonder MFA is een open deur.",
  },
  "2.2": {
    consequence: "Phishing kan leiden tot gestolen accounts, factuurfraude of datalekken.",
    betterSetup: "Gebruik geavanceerde mailbeveiliging, veilige links/bijlagen en periodieke bewustwording voor medewerkers.",
    cloud1Fit: "Cloud ÉÉN kan Microsoft Defender en security-awareness als praktische verbeterstap begeleiden.",
    priority: "hoog",
    risk: "94% van alle malware wordt afgeleverd via e-mail. Eén klik van één medewerker op een phishingmail kan genoeg zijn om uw hele organisatie plat te leggen.",
    firstStep: "Stuur uzelf een test: forward een bekende phishingmail naar uw zakelijk adres. Wordt hij tegengehouden? Zo niet, dan geldt dat ook voor uw medewerkers.",
  },
  "2.3": {
    consequence: "Ransomware of malware wordt later ontdekt wanneer endpointbeveiliging niet centraal wordt bewaakt.",
    betterSetup: "Zorg voor centraal beheerde endpointbeveiliging en actieve opvolging van meldingen.",
    cloud1Fit: "Cloud ÉÉN Werkplek Premium of aanvullende security monitoring kan hierbij helpen.",
    priority: "hoog",
    risk: "Ransomware legt gemiddeld 3 weken een organisatie plat. De gemiddelde herstelkost voor MKB ligt tussen €50.000 en €200.000 — exclusief reputatieschade.",
    firstStep: "Controleer op één laptop of Microsoft Defender actief is en wanneer de laatste scan is uitgevoerd (via Windows Beveiliging → Virusbeveiliging).",
  },
  "2.4": {
    consequence: "Microsoft 365 is geen volledige back-up. Verwijdering, ransomware of fouten kunnen herstel lastig maken.",
    betterSetup: "Gebruik aparte Microsoft 365 back-up met retentie en test periodiek of herstel werkt.",
    cloud1Fit: "Cloud ÉÉN kan back-up en herstel voor Microsoft 365 als aanvullende dienst inrichten en beheren.",
    priority: "hoog",
    risk: "Microsoft garandeert dat hun platform beschikbaar is — niet dat uw data terugkomen na een ongeluk of ransomware. Standaard retentie is slechts 30 dagen.",
    firstStep: "Probeer een e-mail van 60 dagen geleden terug te zetten die 'per ongeluk' is verwijderd. Als dat niet lukt: u heeft geen werkende back-up.",
  },
  "2.5": {
    consequence: "Te brede toegang vergroot de impact van fouten, datalekken en onbedoelde deling.",
    betterSetup: "Werk met rollen, periodieke controle van rechten en signalering op gevoelige informatie.",
    cloud1Fit: "Cloud ÉÉN kan helpen met Microsoft 365 rechtenstructuur, securitybeleid en data-afspraken.",
    priority: "hoog",
    risk: "Als iemand de verkeerde map aanklikt en bestanden versleutelt door ransomware, bepaalt zijn toegangsrecht hoeveel schade er ontstaat. Te ruime rechten betekenen maximale schade.",
    firstStep: "Kies een willekeurige medewerker en bekijk welke SharePoint-mappen hij kan zien. Als hij overal bij kan, is het toegangsbeheer niet op orde.",
  },
  "2.6": {
    consequence: "Bij een incident ontstaat snel tijdverlies, onduidelijkheid en grotere bedrijfsimpact.",
    betterSetup: "Maak een incidentplan, leg contactpersonen vast en oefen herstel en communicatie.",
    cloud1Fit: "Cloud ÉÉN Werkplek Premium en aanvullende securitydiensten passen bij monitoring en incidentvoorbereiding.",
    priority: "hoog",
    risk: "Zonder plan verliest een organisatie bij een incident gemiddeld 4x zoveel tijd. Het eerste uur is cruciaal — en dat is precies het moment waarop iedereen zoekt wie ze moeten bellen.",
    firstStep: "Schrijf op één A4: wat doe je als je 's ochtends de systemen niet kunt bereiken? Wie bel je als eerste? Staat dat nummer ook in uw telefoon?",
  },
  "2.7": {
    consequence: "De mens is de zwakste schakel: de meeste cyberincidenten beginnen met een medewerker die ergens op klikt.",
    betterSetup: "Combineer bewustwordingstraining met periodieke gesimuleerde phishing-aanvallen en meet de voortgang.",
    cloud1Fit: "Cloud ÉÉN kan Microsoft Defender-simulaties en security-awareness als onderdeel van een beveiligd werkplek inrichten.",
    priority: "hoog",
    risk: "80% van de cyberincidenten heeft een menselijke component. Technische maatregelen helpen niet als medewerkers niet weten wat phishing is.",
    firstStep: "Vraag uw team: wat doe je als je een verdachte e-mail ontvangt? Als het antwoord wisselt of onduidelijk is, is bewustwording een prioriteit.",
  },
  "2.8": {
    consequence: "Een back-up die nooit is getest, is geen back-up. Bij een ransomware-aanval kan ongetest herstel fataal zijn voor bedrijfscontinuïteit.",
    betterSetup: "Test back-ups minimaal jaarlijks, leg hersteltijden vast en oefen het volledige herstelscenario met betrokkenen.",
    cloud1Fit: "Cloud ÉÉN kan back-up inclusief hersteltest beheren en documenteren als onderdeel van een beheerpakket.",
    priority: "hoog",
    risk: "58% van de organisaties die een back-up hadden, konden toch niet volledig herstellen — omdat de test nooit was uitgevoerd. Een ongeteste back-up bestaat eigenlijk niet.",
    firstStep: "Plan 2 uur in om één map of mailbox terug te zetten vanuit de back-up. Doe het echt. Documenteer wat lukte en wat niet.",
  },
  "3.1": {
    consequence: "Een internetstoring kan direct invloed hebben op cloudwerkplekken, telefonie en klantcontact.",
    betterSetup: "Gebruik een back-upverbinding en monitoring zodat uitval sneller wordt opgevangen.",
    cloud1Fit: "Cloud ÉÉN kan helpen met KPN EEN connectiviteit, back-upverbindingen en beheer.",
    priority: "middel",
    risk: "Als uw internet uitvalt en u werkt volledig in de cloud, staat uw hele organisatie stil. Hoelang kunt u het werk voortzetten zonder internet?",
    firstStep: "Bereken wat een dag internetstoring kost: aantal medewerkers × uurloon × 8 uur. Dat is het bedrag dat een back-upverbinding maximaal mag kosten.",
  },
  "3.2": {
    consequence: "Een ongescheiden netwerk maakt het moeilijk om gasten, medewerkers en apparaten veilig te scheiden.",
    betterSetup: "Richt zakelijke wifi in met gescheiden netwerken, centraal beheer en monitoring.",
    cloud1Fit: "Cloud ÉÉN kan bedrijfsmatige wifi en netwerkbeheer koppelen aan de werkplekomgeving.",
    priority: "middel",
    risk: "Gasten en medewerkers op hetzelfde wifi-netwerk is als een bezoeker door uw serverruimte laten lopen. Het geeft onbedoeld toegang tot apparaten en bedrijfsdata.",
    firstStep: "Controleer of uw router een gescheiden gastnetwerk heeft. Kunnen gasten bij uw printers en gedeelde mappen? Test het zelf.",
  },
  "3.3": {
    consequence: "Telefonie los van Teams of mobiel werken kan bereikbaarheid en beheer onnodig ingewikkeld maken.",
    betterSetup: "Breng vaste telefonie, mobiel en Teams waar mogelijk dichter bij elkaar.",
    cloud1Fit: "Cloud ÉÉN kan KPN EEN en Teams-telefonie gebruiken als haakje voor modernere communicatie.",
    priority: "middel",
    risk: "Als uw vaste telefoonlijn uitvalt en medewerkers bereikbaar zijn via privénummers, verliest u controle over klantcontact en zakelijke communicatie.",
    firstStep: "Stel de vraag: als iemand morgen uw bedrijfsnummer belt terwijl de telefooncentrale uitvalt, waar komt die terecht? Heeft u dat antwoord?",
  },
  "3.4": {
    consequence: "Prive- of losse abonnementen geven minder grip op kosten, beveiliging en vervanging bij uitval.",
    betterSetup: "Centraliseer zakelijke abonnementen en koppel mobiel beheer aan de werkplek.",
    cloud1Fit: "Cloud ÉÉN kan mobiele abonnementen, toestelbeheer en werkplekbeheer samenbrengen.",
    priority: "middel",
    risk: "Zakelijke data op privéabonnementen valt buiten uw beheer. Bij vertrek van een medewerker kunt u niets wissen, blokkeren of overdragen.",
    firstStep: "Tel hoeveel medewerkers een zakelijk abonnement hebben versus een privéabonnement voor werk. Alles buiten zakelijk beheer is een blinde vlek.",
  },
  "3.5": {
    consequence: "Klanten en collega's krijgen een wisselende ervaring wanneer bereikbaarheid per persoon verschilt.",
    betterSetup: "Maak medewerkers bereikbaar via vaste nummers, mobiel en Teams met duidelijke routering.",
    cloud1Fit: "Cloud ÉÉN kan vast-mobiel en Teams-integratie praktisch begeleiden.",
    priority: "laag",
    risk: "Klanten die uw organisatie niet kunnen bereiken gaan naar de concurrent. Slechte bereikbaarheid is zelden een keuze — het is meestal een gevolg van ongecoördineerde telefonieoplossingen.",
    firstStep: "Bel uw eigen bedrijfsnummer als een klant zou bellen. Komt u snel bij de juiste persoon? Wat als die persoon er niet is?",
  },
  "3.6": {
    consequence: "Los AI-gebruik kan leiden tot datarisico's, onduidelijke werkwijzen en gemiste productiviteitskansen.",
    betterSetup: "Maak afspraken over AI-gebruik, data en training voordat tools breed worden ingezet.",
    cloud1Fit: "Cloud ÉÉN kan helpen met Microsoft 365 Copilot-readiness, adoptie en veilige werkwijzen.",
    priority: "middel",
    risk: "Medewerkers die ChatGPT gebruiken voor klantdata of interne documenten, sturen die data naar servers buiten de EU — zonder dat u dat weet en zonder AVG-compliance.",
    firstStep: "Vraag uw team welke AI-tools ze gebruiken en of ze ooit klantgegevens of interne documenten hebben ingeplakt. De antwoorden zijn verhelderend.",
  },
  "3.7": {
    consequence: "Onveilige externe toegang is een veelgebruikte aanvalsvector. VPN alleen is niet meer genoeg in moderne dreigingslandschappen.",
    betterSetup: "Implementeer een zero-trust aanpak waarbij elke toegangspoging continu wordt beoordeeld op risico.",
    cloud1Fit: "Cloud ÉÉN Werkplek Premium past bij Conditional Access en zero-trust via Microsoft Entra ID.",
    priority: "hoog",
    risk: "Een VPN-verbinding geeft een hacker die één account overneemt meteen toegang tot uw hele netwerk. Zero-trust beperkt de schade tot het specifieke account en apparaat.",
    firstStep: "Controleer of medewerkers via VPN of via Conditional Access in Microsoft 365 werken. Als het antwoord VPN is, is dat het startpunt voor verbetering.",
  },
  "3.8": {
    consequence: "Zonder netwerkmonitoring worden storingen en beveiligingsincidenten te laat ontdekt, wat leidt tot meer uitval en grotere schade.",
    betterSetup: "Implementeer continue netwerkmonitoring met automatische alerting bij afwijkingen in prestaties of verdacht verkeer.",
    cloud1Fit: "Cloud ÉÉN kan KPN EEN-connectiviteit combineren met proactieve monitoring en meldingen voor netwerkstoringen.",
    priority: "middel",
    risk: "De gemiddelde tijd tussen inbraak en ontdekking is 197 dagen. Zonder monitoring loopt een aanvaller maandenlang ongemerkt rond in uw netwerk.",
    firstStep: "Vraag uw IT-beheerder: ontvangen jullie automatisch een melding als er iets afwijkends op het netwerk gebeurt? 'Nee' of 'weet ik niet' betekent: er is werk aan de winkel.",
  },
  "4.1": {
    consequence: "IT wordt reactief geregeld, waardoor storingen langer duren en kennis afhankelijk is van losse personen.",
    betterSetup: "Werk met een vaste IT-partner, duidelijke verantwoordelijkheden en proactieve monitoring.",
    cloud1Fit: "Cloud ÉÉN Werkplek Premium past bij organisaties die proactief beheer en monitoring willen.",
    priority: "hoog",
    risk: "Organisaties zonder vaste IT-partner lossen problemen op als ze er al zijn — reactief, duur, en met meer downtime dan nodig is.",
    firstStep: "Noteer de laatste 5 IT-problemen die zijn opgetreden. Hoe lang duurde het voor ze waren opgelost? Was dat acceptabel? Dat is uw huidige serviceniveau.",
  },
  "4.2": {
    consequence: "Meldingen raken sneller kwijt en gebruikers weten niet wanneer ze geholpen worden.",
    betterSetup: "Gebruik een ticketsysteem met status, prioriteit en afspraken over reactietijden.",
    cloud1Fit: "Cloud ÉÉN kan ondersteuning leveren via duidelijke supportprocessen en beheerafspraken.",
    priority: "middel",
    risk: "Zonder ticketsysteem zijn medewerkers dagelijks kostbare tijd kwijt aan IT-problemen die nergens worden bijgehouden en dus ook nooit structureel worden opgelost.",
    firstStep: "Vraag 5 medewerkers: als je een IT-probleem hebt, wat doe je dan? E-mail? WhatsApp? Iemand aanspreken? Elk ander antwoord toont dat er geen proces is.",
  },
  "4.3": {
    consequence: "Lokale servers vragen onderhoud, back-up en noodscenario's die vaak meer risico en kosten geven.",
    betterSetup: "Onderzoek welke systemen veilig naar de cloud kunnen en beheer de overgebleven omgeving centraal.",
    cloud1Fit: "Cloud ÉÉN Werkplek Standaard of Premium kan helpen richting een moderne cloudwerkplek.",
    priority: "middel",
    risk: "Lokale servers vereisen fysieke beveiliging, onderhoud en noodstroom. Eén brand, overstroming of stroomstoring — en alles is weg.",
    firstStep: "Vraag uw IT-beheerder: wat staat er lokaal op servers dat niet in de cloud staat? Wat zou er verloren gaan als die ruimte morgen verbrand?",
  },
  "4.4": {
    consequence: "Zonder routekaart worden IT-keuzes vaak ad hoc en is budget lastiger te voorspellen.",
    betterSetup: "Maak een 2- tot 3-jaarsplan met kwartaalreviews, prioriteiten en budgetindicatie.",
    cloud1Fit: "Cloud ÉÉN kan als IT-partner helpen met roadmap, kwartaalreview en praktische vervolgstappen.",
    priority: "middel",
    risk: "Zonder IT-roadmap worden vervangingen en upgrades gedaan als iets kapot is — nooit op het juiste moment. Dat is duurder en gevaarlijker dan planmatig werken.",
    firstStep: "Schrijf op welke IT-investeringen u de komende 2 jaar verwacht. Als u dat niet kunt, heeft u geen roadmap — en dus ook geen budgetplanning.",
  },
  "4.5": {
    consequence: "Klantvragen, audits of verzekeringen kosten veel tijd wanneer bewijs en maatregelen niet klaarstaan.",
    betterSetup: "Leg basismaatregelen, beleid, back-up, toegang en incidentafspraken aantoonbaar vast.",
    cloud1Fit: "Cloud ÉÉN Werkplek Premium en securitydiensten kunnen helpen met aantoonbare basismaatregelen.",
    priority: "hoog",
    risk: "Verzekeringsmaatschappijen weigeren steeds vaker cybersclaims als u niet kunt aantonen dat basismaatregelen zijn getroffen. Uw polis is mogelijk minder waard dan u denkt.",
    firstStep: "Lees uw cyberverzekeringspolis. Staat erin dat MFA, back-up en een incidentplan verplicht zijn? Controleer of u aan die voorwaarden voldoet.",
  },
  "4.6": {
    consequence: "Zonder kosteninzicht is lastig te sturen op licenties, werkplekken en groei.",
    betterSetup: "Maak kosten per medewerker inzichtelijk en bespreek jaarlijks optimalisatie en licenties.",
    cloud1Fit: "Cloud ÉÉN kan helpen met voorspelbare werkplekkosten en licentieoptimalisatie.",
    priority: "laag",
    risk: "Organisaties betalen gemiddeld 23% te veel voor IT-licenties omdat niemand bijhoudt wat er is aangeschaft, wie het gebruikt en wat er niet meer nodig is.",
    firstStep: "Vraag een overzicht op van alle actieve Microsoft 365 licenties. Vergelijk het aantal met uw actieve medewerkers. Elke licentie meer is geld dat u weggooit.",
  },
  "4.7": {
    consequence: "Een ontbrekend verwerkingsregister of AVG-beleid kan leiden tot boetes tot €20 miljoen of 4% van de jaaromzet.",
    betterSetup: "Maak een verwerkingsregister, sluit verwerkersovereenkomsten en review jaarlijks of alles nog klopt.",
    cloud1Fit: "Cloud ÉÉN kan helpen met AVG-documentatie, verwerkersovereenkomsten voor Microsoft-diensten en privacyadvies.",
    priority: "hoog",
    risk: "Een datalek zonder verwerkingsregister of verwerkersovereenkomsten kan leiden tot boetes tot €20 miljoen. De kans op een klacht van medewerker of klant is realistischer dan u denkt.",
    firstStep: "Controleer: heeft u een verwerkingsregister, een privacyverklaring op uw website en verwerkersovereenkomsten met Microsoft? Dit zijn de drie basisverplichtingen.",
  },
  "4.8": {
    consequence: "Zonder overzicht van leveranciers en contracten raken afspraken over service, opzegtermijnen en SLA's op de achtergrond.",
    betterSetup: "Houd een leveranciersregister bij met contactpersonen, verloopdatums, SLA's en een jaarlijkse evaluatie.",
    cloud1Fit: "Cloud ÉÉN kan als vaste IT-partner helpen met leveranciersoverzicht en contractadvies.",
    priority: "middel",
    risk: "Contracten die stilzwijgend worden verlengd, kosten organisaties gemiddeld €3.000–€8.000 per jaar aan diensten die ze niet meer nodig hebben of beter kunnen afnemen.",
    firstStep: "Maak een lijst van alle IT-leveranciers en hun contractvervaldatum. Staan er contracten bij die u al jaren automatisch verlengt zonder te evalueren?",
  },
};

export function getQuestionAdvice(questionId: string): QuestionAdvice {
  return QUESTION_ADVICE[questionId];
}
